### PR TITLE
Reinstate day of week on tooltips for the build status chart

### PR DESCRIPTION
**Pull request by sorta**
Fairly straightforward, addresses this issue: https://github.com/travis-ci/travis-insights/issues/71

Not urgent to review, whenever you have time for it is fine 👍

### CODE REVIEW

**Comment by sorta** [comment]
Just noticed that percy is catching some stuff that's always going to be different. I might look into preventing that https://docs.percy.io/docs/percy-specific-css

**Comment by artursmirnov** [comment]
Oh, that seems to be caused by dynamically generated data in tests 🤔

**Comment by sorta** [comment]
Yes, although the dynamic data in the tests _should_ always result in the same pattern, because it just loops through an array of preset values. But what's unavoidable is that the dates will always be different. Anyway, I've set up a separate PR for looking into solving the snapshot issue.

**Comment by sorta** [comment]
Thanks! 😄

**Pull request merged**
