### PR TITLE
User-facing feature flags

### PR DESCRIPTION
**Pull request by clekstro**
This will allow users to experiment with new features and give us feedback before we roll them out for everyone.

### CODE REVIEW

**Comment by clekstro** [comment]
Here's a sample of the current UI I've hacked together (with a sample feature toggled):
featureflags

Would love to start getting feedback as it's functional at this point. Right now just having issues when deploying while Mirage is enabled in production mode.

**Comment by backspace** [comment]
That UI looks fine to me! I love the pink header example 😆

**Comment by clekstro** [comment]
Need to fix whatever tests are currently broken here as well as get the deployment issues resolved so we can start to merge @lislis' work in with this.

**Comment by clekstro** [comment]
The deploy now works as expected as long as Mirage is disabled.  I wonder if this might have something to do with the host/endpoint config. However, it's strange that we don't even get to the point where the app boots.

**Comment by clekstro** [comment]
Ok, the app currently boots, but we're not seeing the same behavior in PR envs that we see when running in production mode locally. The requests to `/features` aren't being properly intercepted by Mirage.

**Comment by clekstro** [comment]
Closing in favor of #683.

**Pull request closed without merging**
