### PR TITLE
remove unnessary(?) things from charmscout script

### PR DESCRIPTION
**Pull request by lislis**
where does the charm key come from?

### CODE REVIEW

**Comment by joshk** [comment]
I think it comes from the ENV, @drogus can you confirm this?

**Comment by simi** [comment]
@lislis it is defined at https://github.com/travis-ci/travis-web/blob/master/config/environment.js#L51

**Comment by joshk** [comment]
Soooooo, do we still need this PR?

**Comment by lislis** [comment]
@joshk probably not, since #371 removes it completely

**Comment by joshk** [comment]
Should we close this PR?

**Comment by lislis** [comment]
do eeeeet

**Pull request closed without merging**
