### PR TITLE
Pj 135 top bar content

### PR DESCRIPTION
**Pull request by paulthegeek**

### CODE REVIEW

**Comment by joshk** [comment]
This looks great!

I think we should either remove `Dashboard` and ship this, or hold off until the Dashboard is finished.

@acnagy @ctrlaltjustine thoughts?

**Comment by ctrlaltjustine** [comment]
I don't think top bar should be blocked by dashboard and don't have a problem with that link being removed until dashboard work is finished.

**Comment by ctrlaltjustine** [comment]
That said, there is still some [feedback that needs to be addressed before it's ready to be shipped](https://github.com/travis-pro/design-tasks/issues/135#issuecomment-411430298).

**Comment by joshk** [comment]
Sounds great to me @ctrlaltjustine , we can ship without the Dashboard

**Pull request merged**
