### PR TITLE
As providers prefix

### PR DESCRIPTION
**Pull request by artursmirnov**
Ticket: https://travisci.assembla.com/spaces/Web/tickets/267/details

### CODE REVIEW

**Comment by sorta** [comment]
Exciting! :tada: I'll start reviewing it :eyes:

**Comment by piotr-travisci** [comment]
Absolutely amazing & huge job @artursmirnov 👏 
Migrate tab also does not work in Organizations, but it shows different error than reported by Emmanuel.
Screenshot 2020-02-03 at 10 08 35

**Comment by piotr-travisci** [comment]
@artursmirnov 
Do you think we should enable `enableBitbucketLogin` flag by default here or in `epic-bb-integration` branch?

**Comment by artursmirnov** [comment]
@piotr-travisci yes, it makes a lot of sense to me 👍 We can either enable it in separate PR or wait until this PR https://github.com/travis-ci/travis-web/pull/2324 by @sorta is merged, which will allow us to easily manage feature flags via ENV vars. What do you think?

**Comment by artursmirnov** [comment]
@sorta @emmanuel-ci @piotr-travisci, thank you all for reviews! 🎉 I think that all of the errors that you've mentioned are caused by the API not supporting provider prefixes yet (this PR deployments use production API). Could you please check them at http://staging.travis-ci.com/ and http://staging.travis-ci.org/? Thanks!

**Comment by sorta** [comment]
Excellent @artursmirnov ! I tested just now on staging and it seems to work as expected :+1:

**Comment by sorta** [comment]
In regards to the `enableBitbucketLogin` flag, the PR https://github.com/travis-ci/travis-web/pull/2324 has been merged into `master`. If/when we are ready for it, we can merge it into `epic-bb-integration` and start using it.

**Pull request merged**
