### PR TITLE
Address issue where job restart buttons are missing sometimes

### PR DESCRIPTION
**Pull request by sorta**
Intended to address this issue https://travisci.assembla.com/spaces/Support/tickets/54--bug--job-restart-button-not-always-appearing-on-build-page/details

### CODE REVIEW

**Comment by sorta** [comment]
I'm able to reproduce the issue at https://travis-ci.com/travis-ci/travis-api/builds/137388749

**Comment by sorta** [comment]
Excellent :smile: Thanks for the reviews @artursmirnov & @piotr-travisci!

**Comment by Datamance** [comment]
Odd - still seeing this in the latest version of chrome (79.0.3945.88) but not Safari.

**Comment by artursmirnov** [comment]
Hey @Datamance, thanks for reaching out! Could you please give us an example of the build where the issue appears? It could be a private repository too. If you'd prefer to share the details privately, please reach out to our support linking to this issue and we'll catch it up from there.

**Comment by Datamance** [comment]
Hey @artursmirnov , thanks for reaching out - unfortunately, after visiting the site in Safari and then kicking off a build, I can no longer reproduce the bug :/

I'll let you know if that changes in the near future - again, sorry for the bother!

**Pull request merged**
