### PR TITLE
Add banner for enterprise trial notice

### PR DESCRIPTION
**Pull request by backspace**
This is quite preliminary.

### CODE REVIEW

**Comment by backspace** [comment]
Here’s an example of how it looks when a non-trial license is expiring:

image

Expired trial license:

image

Expiring trial license:

image

Note that these all are “First time here?” because I didn’t add any repositories or builds or the like to the tests I used to generate these, but they’ll look the same atop any page.

**Comment by joshk** [comment]
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by danishkhan** [comment]
THIS IS AMAZING!

**Comment by joshk** [comment]
@bnferguson YOU SHOULD CHECK THIS OUT!

**Comment by bnferguson** [comment]
OH. MY. GOD. ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️  

This is great!

**Comment by backspace** [comment]
Thank you all. This work is wholly based on a sample API request @joshk showed me and some pseudocode to determine when/what should be shown. I’m not aware of how this can be tested in a production environment, is that currently possible? It would be nice to get confirmation that it actually works. Let me know if there’s anything I can provide to facilitate that.

Once it’s verified to work, I can give it a once-over, remove the screenshot code I added due to laziness, and then it can be merged, since it should have no impact on non-enterprise deployments.

**Comment by danishkhan** [comment]
@bnferguson can we cut a 2.1.7-beta to test this out and if things are :+1: remove the screenshot code and cut a 2.1.7 release for GA?

**Comment by backspace** [comment]
Any word on this @bnferguson or @danishkhan?

**Comment by bnferguson** [comment]
@backspace So sorry for the lack of response! I'll try to check this in Enterprise on Monday or Tuesday!

**Comment by bnferguson** [comment]
travis ci - enterprise 2017-07-10 16-17-37

@backspace I'm seeing this both on te-dev.travis-ci.com (which has no replicated) and on https://te.volcanicislandfortress.com. From what I'm seeing this relies on the Replicated Integration API? Experimenting with it, it looks like this is available inside the container when replicated is running but not externally for an application like `travis-web` (that is, https://10.69.10.30:9880/license/v1/license and others isn't publicly accessible as it contains sensitive info). 

Looks like we'll need to wrap the needed endpoints in our own api and publish them. 

Inside the container I was able to `curl` things just fine (but strangely the env var didn't get automatically passed in, I ended up manually setting it for now, and this can be figured out later). 

So I guess the next step on this would be getting an API end point in `travis-api` that publishes info that `travis-web` can consume?

**Comment by backspace** [comment]
gah, that’s a nuance I was unaware of, but I think I understand now that you point it out.

So `travis-api` runs inside the same container, right? (Or `travis-pro-api`?) It would probably make sense to have the Travis API consume the Replicated API and transform it somehow.

We also have a long-standing feature request on the API to produce billing/subscription information for .com accounts, but hopefully I can see this through more quickly.

**Comment by bnferguson** [comment]
> gah, that’s a nuance I was unaware of, but I think I understand now that you point it out.

Yeah, same here. This is the first time we've done anything with this API. 

> So travis-api runs inside the same container, right? (Or travis-pro-api?) It would probably make sense to have the Travis API consume the Replicated API and transform it somehow.

Yup! We currently ship `travis-pro-api` though after the big merge I guess that'll just be `travis-api`? Having Travis consume that API what makes sense to me too.

**Comment by backspace** [comment]
I‘ve opened an issue for this and I’m going to close this PR for now, since it relies on things that aren’t actually possible. I’ll be able to salvage the useful code when the time comes.

**Pull request closed without merging**
