### PR TITLE
Address svgjar warnings

### PR DESCRIPTION
**Pull request by lislis**
ids, and viewBox

### CODE REVIEW

**Comment by backspace** [comment]
This makes me wonder whether we should have the team page as a Percy screenshot? 🤔

**Comment by backspace** [comment]
BUT thanks for addressing this, I kept meaning to and then failing hehe

**Comment by lislis** [comment]
That makes sense, I can add that here as well

**Comment by lislis** [comment]
I fixed the one regression and added snapshots of the about, plans and logo page

**Comment by backspace** [comment]
Excellent!

**Pull request merged**
