### PR TITLE
*.scss: fix typos

### PR DESCRIPTION
**Pull request by the-j0k3r**
There are probably more but this is as far I I was.

edit

there is this  @ line 201 https://github.com/travis-ci/travis-web/blob/96b4b0e4f54cb3157b944814ee25caca2ab612e6/app/styles/app/layouts/profile.scss#L201 introduced in #1520

Should be a value there no idea what it was intended for that `em` if I had to guess Id say `0.5em`
if you wish, I can push that in here also.

### CODE REVIEW

**Comment by backspace** [comment]
Hey, thanks for this. I have a giant PR that’s awaiting cleanup and merging and I don’t want to introduce any merge conflicts, so I’ll look at this again after that‘s done.

**Comment by the-j0k3r** [comment]
No problem, I stumbled across this while making a dark style for travis-ci based on the generated css.

Where is that PR of yours? Ide hate to have spent hours on making a dark style that wont work after that...

**Comment by backspace** [comment]
Sorry, I should have linked to it. It’s [here](https://github.com/travis-ci/travis-web/pull/1604), it’s the updates for GitHub Apps support and the displaying of open source repositories at travis-ci.com. It’s my plan this week to break it up into some more-manageable parts and merge them.

**Comment by the-j0k3r** [comment]
> heh well it wasn’t trivial to me, it’s been the major work of the past month.

I meant the only conflict file is only two lines maybe even just one, The rebase operation should handle it automatically and if you use Atom its shouldn't make much noise if it does.

 I didnt mean the work you did was trivial :D that trivial definitely is not sir, most certainly not.

**Comment by the-j0k3r** [comment]
@backspace there we go all done and rebased against master.

**Comment by backspace** [comment]
I ended up adding another commit in #1656 as the `display: flex` was a mistaken inclusion. Thanks for finding these!

**Comment by the-j0k3r** [comment]
Not very nice to remove my contribution in this manner.

**Comment by backspace** [comment]
I mentioned you in the squashed commit and linked to your PR, I don’t understand how that’s a removal. Do you have a recommendation on what I could have done differently?

My recommendation to you is to [allow edits from maintainers](https://github.com/travis-ci/travis-web/pull/1644#issuecomment-387908325), I wouldn’t have had to make my own PR that way.

**Comment by the-j0k3r** [comment]
> I mentioned you in the squashed commit and linked to your PR

Not same thing according to how GitHub tracks contributions but... OK...

> Do you have a recommendation on what I could have done differently?

Yes.

> My recommendation to you is to allow edits from maintainers, I wouldn’t have had to make my own PR that way.

You could have asked or made a review/comment or something, that's what these issue thinga-me-bobs are for no?

:+1:

**Comment by backspace** [comment]
Was your goal to get onto the contributor list on GitHub? If so, you could make an empty commit PR and I’ll merge it.

I have a limited amount of time to engage in this kind of work and I didn’t want to wait for your response.

**Comment by joshk** [comment]
@the-j0k3r your help and contributions are really appreciated. Thank you!

**Pull request closed without merging**
