### PR TITLE
Updating the banner explaining which deprecated xcode versions get...

### PR DESCRIPTION
**Pull request by kdaniels**
...built where. As part of [this](https://docs.travis-ci.com/user/build-environment-updates/2017-08-17/).

### CODE REVIEW

**Comment by lislis** [comment]
@kdaniels do you want to merge yourself should I?

**Comment by kdaniels** [comment]
@lislis I'm in and out most of the day today, so if you're up for handling this one that'd be fine with me :)

**Comment by lislis** [comment]
@kdaniels will 🚢 then! Thanks for the change!

**Comment by kdaniels** [comment]
@lislis thanks! 😄

**Pull request merged**
