### PR TITLE
Bug fix cycle 11

### PR DESCRIPTION
**Pull request by murtaza-swati**
Bug fix cycle 11

### CODE REVIEW

**Comment by murtaza-swati** [comment]
@Jullianos this is a common PR where all the fixes of FixPack cycle 11 have been merged into.
I have deployed this bug-fix-cycle-11 branch to https://app-staging-dev1.travis-ci.com and I have found an issue.

When you visit the plan page https://app-staging-dev1.travis-ci.com/account/plan it seems the "Change Plan", "Buy Addons" and "Cancel Subscription" buttons have stopped working, clicking on any of them doesn't do anything.
Screenshot 2022-08-22 at 2 23 56 PM


I believe the changes done for the FixPack cycle 11 tickets have caused this issue. Can you please check this?
CC: @AndriiMysko @RatGabi

**Comment by Jullianos** [comment]
@murtaza-swati I have manually reverted all my changes and none of them fixed the issue. On my side the whole "Plan" tab is invisible if no plan is already selected. Additionally none of my changes were directly related to this issue.
CC: @AndriiMysko, @RatGabi

**Comment by RatGabi** [comment]
I deployed https://github.com/travis-ci/travis-web/pull/2722/commits/a97609441ec61d365b794281af8993d86cc7cdba (which is my only commit here) to qe staging and the problem didn't reproduce and then I deployed "bug-fix-cycle-11" and the problem reproduced. I don't think that my commit caused it.

**Comment by AndriiMysko** [comment]
@Jullianos Hello. The error is in this commit https://github.com/travis-ci/travis-web/pull/2722/commits/797f97f1d1cd46820a9f42222cacc3feecc92b63 and the message is `can't access property \"get\", this.get(...) is undefined` on line `    const userUsage = this.get('account').get('allowance').get('userUsage');`
Could you please check?

**Comment by murtaza-swati** [comment]
@Jullianos it seems the problem was not solved by https://github.com/travis-ci/travis-web/pull/2723

**Comment by Jullianos** [comment]
> @Jullianos it seems the problem was not solved by #2723

@murtaza-swati The problem with the plan tab not showing and the "Change Plan", "Buy Addons" and "Cancel Subscription" buttons not working? Because I'm not sure that these latest changes were related to that. The changes from https://github.com/travis-ci/travis-web/pull/2723 were only for the profile-nav. But I'm going to try again and see if I can locate the issue.

**Comment by murtaza-swati** [comment]
> > @Jullianos it seems the problem was not solved by #2723
> 
> @murtaza-swati The problem with the plan tab not showing and the "Change Plan", "Buy Addons" and "Cancel Subscription" buttons not working? Because I'm not sure that these latest changes were related to that. The changes from #2723 were only for the profile-nav. But I'm going to try again and see if I can locate the issue.

oh sorry @Jullianos I thought it was also supposed to fix the "Change Plan", "Buy Addons" and "Cancel Subscription" buttons not working issue.
Thanks, please just let me know when I should check this.

**Comment by murtaza-swati** [comment]
@Jullianos thank you! It looks like https://github.com/travis-ci/travis-web/pull/2724 fixed the problem with the buttons being unresponsive.

**Pull request merged**
