### PR TITLE
add aria-labels to jobs-item

### PR DESCRIPTION
**Pull request by lislis**

### CODE REVIEW

**Comment by joshk** [comment]
screenshot?

**Comment by lislis** [comment]
@joshk there is no visual difference, it's just an attribute for screenreaders to use
screen shot 2016-01-04 at 14 04 42

I'll keep an eye on these things in the future, we should have this in all the templates imo

**Comment by joshk** [comment]
ahhhhhh, sweet!

**Comment by lislis** [comment]
rebased!

**Pull request merged**
