### PR TITLE
Repo activate button for github apps

### PR DESCRIPTION
**Pull request by sorta**

### CODE REVIEW

**Comment by joshk** [comment]
Oh, one thing to note, is that `.org` and Enterprise don't use GitHub Apps, does this fallback to the old way for them?

**Comment by sorta** [comment]
Yes it should fallback to the old way for `.org`. Not sure about Enterprise, I'll do some testing to verify.

**Comment by backspace** [comment]
I think [this line](https://github.com/travis-ci/travis-web/pull/1792/files#diff-096e8a56e2f38bc2b06dd1206dc06eccR10) that checks for `config.githubApps`, makes it work 😀

**Comment by joshk** [comment]
Ahhhhhh, awesome! Super High 5!

**Comment by sorta** [comment]
Ok I tested and confirmed that `org` and Enterprise fall back to the old method. I've also added in the changes to the manage button.

**Comment by joshk** [comment]
awesome! well, feel free to ship at your convenience! :)

**Comment by sorta** [comment]
Excellent! Will get that going :smiley:

**Pull request merged**
