### PR TITLE
Increase form label text size

### PR DESCRIPTION
**Pull request by artursmirnov**
Issue: https://github.com/travis-ci/bugs-questions-comments-ideas/issues/119

### CODE REVIEW

**Comment by sorta** [comment]
Although, I just noticed that the overlay background seems out of place in Percy. It doesn't seem to happen in browser for me, but might be worth double checking.

**Comment by artursmirnov** [comment]
@sorta thanks for review 😄

**Comment by artursmirnov** [comment]
re: overlay, I think, it's because of the animation. Liquid Fire performs animations via Javascript, so I assume, that Percy takes screenshot during the animation. Let's see how it goes, and if it would show different diffs, then I'll disable animations for testing.

**Comment by sorta** [comment]
Cool, yeah that makes sense and sounds like a good plan 👍

**Pull request merged**
