### PR TITLE
bring back branch name

### PR DESCRIPTION
**Pull request by lislis**

### CODE REVIEW

**Comment by joshk** [comment]
could you add a screenshot please?

**Comment by lislis** [comment]
@joshk here you go
screen shot 2016-01-04 at 15 40 37

**Comment by joshk** [comment]
Fantastic! Looks great!

**Comment by BanzaiMan** [comment]
I was wondering earlier today where it'd gone!

**Comment by drogus** [comment]
@lislis it seems that it's one of the places that I missed when I was feature flagging V3 work. 

Could you change to be in a similar fashion to what I did in `Repo`, ie. add different branch definitions depending on a feature flag?

Something like:

```javascript
import Config from 'travis/config/environment';

var Build;

if(Config.useV3API) {
  Build = DS.Model.extend({
    branch: DS.belongsTo('branch', { async: false, inverse: 'builds' }),
    branchName: Ember.computed.alias('branch.name');
  });
} else {
  Build = DS.Model.extend({
    branchName: Ember.computed.alias('commit.branch');
  });
}

Build.reopen({
  // rest of the stuff
});
```

That way you will be able to use `build.branchName` in the template regardless what data model we use.

In the `Job` model you could do an alias to `build.branchName`:

```
branchName: Ember.computed.alias('build.branchName')
```

Let me know if you have any questions. Also, please remember to rebase, I merged javascript transition.

**Comment by lislis** [comment]
rebased!

**Pull request merged**
