### PR TITLE
Lossless image optimize

### PR DESCRIPTION
**Pull request by PeterDaveHello**
cc #658
```
 public/images/favicon-gray.png                            | Bin 1633 -> 1340 bytes
 public/images/favicon-green.png                           | Bin 1748 -> 1478 bytes
 public/images/favicon-red.png                             | Bin 2213 -> 1551 bytes
 public/images/favicon-yellow.png                          | Bin 2854 -> 1539 bytes
 public/images/favicon.png                                 | Bin 1928 -> 1614 bytes
 public/images/getting-started/build-email-03.png          | Bin 109771 -> 96284 bytes
 public/images/getting-started/build-email.png             | Bin 110549 -> 96283 bytes
 public/images/getting-started/first-build.png             | Bin 147491 -> 133867 bytes
 public/images/getting-started/first-project-no-recent.png | Bin 146324 -> 132687 bytes
 public/images/getting-started/mustache-no-spin.png        | Bin 20559 -> 19041 bytes
 public/images/getting-started/project-switch.png          | Bin 104284 -> 94617 bytes
 public/images/getting-started/project_switch.png          | Bin 25175 -> 20490 bytes
 public/images/landing-page/alex.png                       | Bin 35318 -> 29353 bytes
 public/images/landing-page/chris.png                      | Bin 48025 -> 38688 bytes
 public/images/landing-page/dhh.png                        | Bin 31642 -> 28295 bytes
 public/images/landing-page/laptop.png                     | Bin 495501 -> 455001 bytes
 public/images/layout/made-in-berlin-badge.png             | Bin 6935 -> 6399 bytes
 public/images/layout/travis-logo.png                      | Bin 18699 -> 16230 bytes
 public/images/logos/Tessa-1.png                           | Bin 428395 -> 281878 bytes
 public/images/logos/Tessa-2.png                           | Bin 430292 -> 283062 bytes
 public/images/logos/Tessa-3.png                           | Bin 420538 -> 280835 bytes
 public/images/logos/Tessa-4.png                           | Bin 415075 -> 278376 bytes
 public/images/logos/Tessa-pride-4.png                     | Bin 129079 -> 77567 bytes
 public/images/logos/Tessa-pride.png                       | Bin 129928 -> 77999 bytes
 public/images/logos/TravisCI-Full-Color-light.png         | Bin 25991 -> 15541 bytes
 public/images/logos/TravisCI-Full-Color-vertical.png      | Bin 11155 -> 6610 bytes
 public/images/logos/TravisCI-Full-Color.png               | Bin 26278 -> 15321 bytes
 public/images/logos/TravisCI-Mascot-1.png                 | Bin 45667 -> 26749 bytes
 public/images/logos/TravisCI-Mascot-2.png                 | Bin 45604 -> 26749 bytes
 public/images/logos/TravisCI-Mascot-3.png                 | Bin 45308 -> 26564 bytes
 public/images/logos/TravisCI-Mascot-4.png                 | Bin 44917 -> 26375 bytes
 public/images/logos/TravisCI-Mascot-blue.png              | Bin 45569 -> 26494 bytes
 public/images/logos/TravisCI-Mascot-grey.png              | Bin 43203 -> 26085 bytes
 public/images/logos/TravisCI-Mascot-pride-4.png           | Bin 91369 -> 55458 bytes
 public/images/logos/TravisCI-Mascot-pride.png             | Bin 93770 -> 55337 bytes
 public/images/logos/TravisCI-Mascot-red.png               | Bin 45769 -> 26467 bytes
 public/images/logos/logo-dark-bg-blue.png                 | Bin 5311 -> 3755 bytes
 public/images/logos/logo-light-bg-grey.png                | Bin 4798 -> 3397 bytes
 public/images/logos/logo-light-bg-red.png                 | Bin 5318 -> 3794 bytes
 public/images/logos/mascot-bg-blue.png                    | Bin 23466 -> 13295 bytes
 public/images/logos/mascot-bg-grey.png                    | Bin 23297 -> 13390 bytes
 public/images/logos/mascot-bg-red.png                     | Bin 23515 -> 13353 bytes
 public/images/mailer/arrow-error.png                      | Bin 1748 -> 1724 bytes
 public/images/mailer/arrow-failed.png                     | Bin 1766 -> 1740 bytes
 public/images/mailer/arrow-success.png                    | Bin 1784 -> 1745 bytes
 public/images/mailer/canceled-header-bg.png               | Bin 1288 -> 1071 bytes
 public/images/mailer/clock.png                            | Bin 2138 -> 1311 bytes
 public/images/mailer/email-footer-travis-logo.png         | Bin 3064 -> 1852 bytes
 public/images/mailer/error.png                            | Bin 1074 -> 559 bytes
 public/images/mailer/errored-header-bg.png                | Bin 1288 -> 1071 bytes
 public/images/mailer/failed-header-bg.png                 | Bin 3317 -> 1925 bytes
 public/images/mailer/failed.png                           | Bin 996 -> 589 bytes
 public/images/mailer/footer-logo-38x38.png                | Bin 391 -> 385 bytes
 public/images/mailer/mascot-avatar-15px.png               | Bin 1978 -> 1948 bytes
 public/images/mailer/mascot-avatar-40px.png               | Bin 5435 -> 5363 bytes
 public/images/mailer/passed-header-bg.png                 | Bin 2280 -> 1966 bytes
 public/images/mailer/please-donate.png                    | Bin 2477 -> 2344 bytes
 public/images/mailer/stopwatch-error.png                  | Bin 1472 -> 893 bytes
 public/images/mailer/stopwatch-failed.png                 | Bin 1631 -> 1006 bytes
 public/images/mailer/stopwatch-success.png                | Bin 1627 -> 998 bytes
 public/images/mailer/success.png                          | Bin 893 -> 547 bytes
 public/images/mailer/travis-mascot.png                    | Bin 60902 -> 51789 bytes
 public/images/travis-crying.png                           | Bin 25710 -> 20641 bytes
 public/images/travis-mascot-150.png                       | Bin 40186 -> 34056 bytes
 public/images/ui/default-avatar.png                       | Bin 840 -> 388 bytes
```
```
 public/images/getting-started/build-email.jpg | Bin 55606 -> 46998 bytes
 public/images/getting-started/first-build.jpg | Bin 70036 -> 64936 bytes
 public/images/getting-started/new-project.jpg | Bin 70036 -> 64936 bytes
 public/images/rgsoc.jpg                       | Bin 26547 -> 24084 bytes
 public/images/team/team-lili.jpg              | Bin 22610 -> 17079 bytes
```

### CODE REVIEW

**Comment by clekstro** [comment]
@PeterDaveHello Thanks for submitting this!

Another reason we avoided merging the previous PR was our inability to quickly review the image diffs for quality/content. Given Github's [limit](https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/#diff-limits) of 25 for reviewing binary diffs, would it be possible for you to split up the commits so the images can all be reviewed online? This would help speed up our review considerably.

**Comment by PeterDaveHello** [comment]
Actually, I'll respectfully suggest you to fetch the pull request (something like `git fetch pull/853/head:853`) and review locally, since that'll be the fastest way, and we can do some more precise testing/validation locally, instead of eyes only review, we should find a good enough reason to split the commit again, they are now both meaningful, and atomic, split for just review may make no sense, what do you think?

**Comment by clekstro** [comment]
@PeterDaveHello My suggestion wasn't meant as criticism of how the commits are currently structured. It's just that Github actually does a pretty good job of displaying image diffs side-by-side, without any additional effort/overhead for the reviewer. I'd also like for others on the team to have an opportunity to review the PR given their personal photos are some of those being optimized. I apologize if you find that unreasonable. I can split the commits up if you'd prefer, though it might take me a bit to get to it given my current workload.

**Comment by PeterDaveHello** [comment]
@clekstro I separate the commits.

**Comment by PeterDaveHello** [comment]
https://github.com/travis-ci/travis-web/pull/853/commits/ce5800329a93dd87276a87b2208fba61531959d8#diff-c8413e7efa9f0e2277d1b5dd3cd45dd7 this one makes no sense, I could revert it.

**Comment by clekstro** [comment]
Apologies for the many duplicate comments. I meant to comment on each commit individually, but the review button seems to place them here without any context. Besides @lilikui's picture, this seems fine to me.

**Comment by PeterDaveHello** [comment]
@clekstro updates, thanks for your review.

**Pull request merged**
