### PR TITLE
Add Codecov as integrations solution

### PR DESCRIPTION
**Pull request by stevepeak**
Hey friends,

Steve, founder and CTO of Codecov, I would like to add Codecov into Travis CI as an integration solution for customers. First off, thank you for providing an incredible CI platform; keep up the great work!

In this pull request, you will find the appropriate adjustments to add a Codecov button/popup,
simular to the Code Climate integration.

We have deployed our [integrations page with Travis CI](https://codecov.io/integrations/travis-ci) where customers will be redirected. All our [examples repos](https://github.com/codecov?query=example) have Travis-CI as the featured CI provider.

I hope this pull request will be accepted and both Travis CI and Codecov can continue to offer high quality service to the open source community.

Best Regards,
Steve Peak

> Feel free anytime to [email](mailto:steve@codecov.io) or chat on IRC #codecov iopeak

### CODE REVIEW

**Comment by joshk** [comment]
Hey Steve

Thanks for the great PR, as well as the email late last week.

I'll reply via email where we can chat about this more.

Talk to you soon!

Josh

**Comment by stevepeak** [comment]
Hey @joshk, checking in to see if you had time to review this. I was really hoping to have this integration complete before the Dublin Web Summit tomorrow, where Codecov will be presenting.

Please let me know what information I can provide to move forward. Hope you had a great weekend!

Thank you,
Steve

**Comment by joshk** [comment]
Hi Steve, 




Sorry but I was on holiday last week, and am jumping on a flight to our company offsite right now. 




I won't have time to review this before tomorrow sorry. I will reply to your original email to our support address soon, and happy to jump on a call sometime next week too. 




Have a great time at the conference and in Dublin!




Josh

**Comment by stevepeak** [comment]
Hey @joshk, just checking in to see if you had time this week to chat? Thank you!

**Comment by joshk** [comment]
Hey Steve,

I am sorry for my radio silence.

I am in Amsterdam today but will be back in Berlin on Wednesday. Maybe we can jump on a call then?

**Comment by stevepeak** [comment]
Wednesday would be great. Lets shoot for 15:00 GMT+1, does that work?
I was in Germany late Sept and Amsterdam all of October, what amazing cities!
Thanks

**Comment by stevepeak** [comment]
@joshk I'm free if you are available. I'm GMT-5.

**Comment by backspace** [comment]
Hey @stevepeak, is getting this merged still an interest of yours?

**Comment by stevepeak** [comment]
@backspace absolutely 👍 Let me know if you need any information from us. We have a major release coming out Sunday so this is perfect timing!

**Comment by backspace** [comment]
I just started at Travis so I was surveying existing pull requests. Sunday seems unlikely to me to get this merged, I’m sorry for giving false hope! I’ll check in with @joshk about what needs to happen on this.

**Comment by stevepeak** [comment]
Welcome aboard ;) I understand, let me know how I can help. Cheers!

**Comment by clekstro** [comment]
It looks like this would still need to have the CoffeeScript converted to JavaScript 😸

**Pull request closed without merging**
