### PR TITLE
Continuous visual integration with Percy

### PR DESCRIPTION
**Pull request by fotinakis**
(chatted with @joshk and @backspace at GitHub Universe about this — basically, here's a fully-integrated visual testing solution for travis-web if you want it! :) )

After this PR, you would see a new commit status on future PRs:

screen shot 2016-09-12 at 10 13 10 pm
screen shot 2016-09-12 at 10 13 49 pm

^ notice that your tests pass, but there were visual changes that Percy caught which need review. Just look through the screenshots in Percy, click Approve if the changes are ok and it'll be green!

Here's what this looks like in Percy:

screen shot 2016-09-19 at 11 25 50 am
screen shot 2016-09-19 at 11 26 26 am

And here's what it looks like if we change `$turf-green: #39aa56` into `$turf-green: blue`:

screen shot 2016-09-19 at 11 26 58 am

Including responsive visual diffs!

screen shot 2016-09-19 at 11 28 46 am

Because I'm a nerd, here's a demo video: http://www.youtube.com/watch?v=MrikhPRczJQ

**Impact on test speed:** zero! Percy is totally architected around "DOM snapshots" and handles rendering entirely in our service outside of your test suite. This allows to do things like [freeze animations](https://blog.percy.io/freezing-animations-in-visual-regression-tests-e6db56a7b3a5) so they don't create noisy diffs, and heavily parallelize the rendering underneath (if you're interested, [here's a talk I gave at RailsConf](https://www.youtube.com/watch?v=5h-JJ2wqiIw) this year about why these are hard problems).

**Setup work needed:**
- You'd need to do the "Setup" steps for Percy — 1) login to Percy, 2) enable the **travis-ci/travis-web** repo, 3) set the `PERCY_TOKEN` and `PERCY_PROJECT=travis-ci/travis-web` env vars in your Travis repo settings. See https://percy.io/docs/setup/travis-ci for more info. 
- You'd need to sign up! :) I did some quick calculations (~100 travis-web builds over the last 15 days, 90 snapshots per build = ~18,000 snapshots/month) so I think our Medium ($149) or Large ($299) [plans](https://percy.io/pricing) would cover you for a long time.

**Future work:**
- Tuning your visual coverage. Removing snapshots where you might not care, adding more of them where you do. Adding snapshots when you catch a visual regression.
- Supporting builds from forks (chatted with @joshk about this, one day we'd love a way to re-run Travis builds with secure env vars present, or some other workaround for the fork security problem).
- Deeper travis integration! :)
- We're working on making Percy builds publicly accessible/linkable, which I assume you would use. 

Docs: https://percy.io/docs/clients/javascript/ember
Blog post: https://blog.percy.io/continuous-visual-integration-for-ember-d9c438e7c4fa

If you decide to do this, this PR is "safe" to merge if tests pass—Percy doesn't enable itself until you set up the environment variables. And of course, let me know if I can help at all.

### CODE REVIEW

**Comment by backspace** [comment]
Thanks for this, @fotinakis! I’ll discuss this with my `travis-web` colleagues and get back to you. Exciting!

**Comment by backspace** [comment]
I haven’t forgotten about this! I’m talking to various interested parties.

**Comment by fotinakis** [comment]
Sounds good, no rush from me! Let me know if anybody has any questions I can help with.

**Comment by backspace** [comment]
We’ve got our trial Percy account now and I’ve opened [this pull request](https://github.com/travis-ci/travis-web/pull/780) to refine the work you‘ve started here, so I’m going to close this. Thanks for getting us going!

I have a font question but I’ll use Intercom, which I assume is preferable for you.

**Pull request closed without merging**
