### PR TITLE
Upgrade x-select to 3.x

### PR DESCRIPTION
**Pull request by Robdel12**
This is currently working off of x-select master because I want to
make sure there aren't any bugs before cutting 3.0. All the tests
pass! But I can't seem to poke around running the server to verify.

### CODE REVIEW

**Comment by backspace** [comment]
oooh, thanks for getting started! I was planning to get to this soonish, I didn’t actually realise the v3 change was happening until I was looking into that Edge problem.

What’s happening with running the server? Does it not let you log in properly?

**Comment by Robdel12** [comment]
Heh, I quickly started the server and got a blank white screen. Then hopped right into tests. 

Just gave it another shot and everything works beautifully :D I took some notes while upgrading so I'm going to incorporate those into the [migration guide](https://emberx-select.pagefrontapp.com/migration-guide) and then probably cut 3.x

**Comment by backspace** [comment]
Excellent!

Do you at The Frontside prefer to avoid the `mut` technique and use controller actions instead?

**Comment by Robdel12** [comment]
We actually prefer the template mut helper but I fell back to old habits this AM :p

**Comment by backspace** [comment]
hah no problem. I didn’t really even “get” `mut` until recently but it seems like it’s nice in this case. Thanks for all your attention on this!

**Comment by Robdel12** [comment]
It took me a little while for it to click with me too. Lots of watching @flexyford & @cowboyd using awesome template helpers.

And no problem! I've been enjoying my 2 weeks of OS time :)

**Comment by backspace** [comment]
ah that’s a great end-of-year activity!

I’ve run this locally to confirm that all is well. Merging!

**Pull request merged**
