### PR TITLE
Run svgo against svg icons

### PR DESCRIPTION
**Pull request by clekstro**

### CODE REVIEW

**Comment by clekstro** [comment]
@backspace @lislis any concerns with this? No visual diffs in percy, so I don't think there's a high risk of any resulting UI bugs.

**Comment by lislis** [comment]
👍 looks like mostly reduced whitespace and removed`g` elements and attributes. Should be fine

**Comment by backspace** [comment]
yeah, fine with me!

**Comment by backspace** [comment]
er…

**Pull request merged**
