### PR TITLE
Add Buck to team page

### PR DESCRIPTION
**Pull request by backspace**
Here is my new submission.

### CODE REVIEW

**Comment by clekstro** [comment]
This looks pretty great

**Comment by backspace** [comment]
Hey, @saltinejustine, how do these assets look for sizing etc?

(Note that the test failures are spurious, the result of canceled builds for UI experimentation)

**Comment by saltinejustine** [comment]
@backspace looks good! just one thing, the portrait img should be sized down to 226x226px which is our retina size. Gif size is good. If you fix that, you may deploy that to the team page!

**Comment by backspace** [comment]
226px it is! 🎉

**Pull request merged**
