### PR TITLE
Ownerpage newstyle

### PR DESCRIPTION
**Pull request by lislis**
refresh the ownerpage

### CODE REVIEW

**Comment by joshk** [comment]
This is fantastic, thank you @saltinejustine and @lislis

**Comment by joshk** [comment]
Should we also add the changes to the Repo page title?

**Comment by lislis** [comment]
@joshk yiss! On it. Would this be the only place for now to link to the owner page?

**Comment by lislis** [comment]
bababababaaaaaaa
screen shot 2015-08-12 at 10 53 34

**Comment by lislis** [comment]
update
screen shot 2015-08-12 at 10 56 56

**Comment by joshk** [comment]
perfecto!

**Comment by lislis** [comment]
Also @saltinejustine 
screen shot 2015-08-12 at 11 02 22

**Comment by saltinejustine** [comment]
@lislis YESSSSSSSS. That reminds me, we need to change our avatars across the board.

**Comment by lislis** [comment]
Also adding a notice if a :owner has no repos. Current status:
screen shot 2015-08-13 at 14 47 25
Awaiting illustration :)

**Comment by saltinejustine** [comment]
Tractor 🔜

**Comment by saltinejustine** [comment]
screen shot 2015-08-14 at 5 50 35 pm-01

**Comment by joshk** [comment]
Wow, awesome!

Also, Lisa, sorry I did not answer you before, but yes, this is the only link to the owner page, at least for now.

**Pull request merged**
