### PR TITLE
Fix plan page route

### PR DESCRIPTION
**Pull request by AndriiMysko**
Hello @artursmirnov 
This PR should fix the merged version of my previous PR and epic-pricing, since you mentioned that it didn't work. Also I've adjusted some icons in the plan selection page. Please take a look.

### CODE REVIEW

**Review by artursmirnov — DISMISSED** [review]
Hey @AndriiMysko, thank you for the fix, it looks good to me 👍 

We have recently merged a minor unrelated change to the billing section in `master` and I have updated the `epic-pricing` accordingly. Could you please pull the update in to your branch and double-check if everything is still working as expected? Thank you!

**Comment by artursmirnov** [comment]
Also there's a test failure that might be related to your changes: https://travis-ci.com/github/travis-ci/travis-web/builds/184208595#L327

**Comment by AndriiMysko** [comment]
@artursmirnov Checked with the latest changes, seems to me everything's working fine. Thank you.

**Review by artursmirnov — APPROVED** [review]
Nice, thank you for checking 👍

**Pull request merged**
