### PR TITLE
Travis vs jenkins page

### PR DESCRIPTION
**Pull request by sorta**
For https://travisci.assembla.com/spaces/Web/tickets/243/details

Test URLs:
- https://epic-tvj-add-page-production.test-deployments.travis-ci.com/travisci-vs-jenkins
- https://epic-tvj-add-page-production.test-deployments.travis-ci.org/travisci-vs-jenkins

Staging Test URLs:
- https://epic-tvj-add-page-staging.test-deployments.travis-ci.com/travisci-vs-jenkins
- https://epic-tvj-add-page-staging.test-deployments.travis-ci.org/travisci-vs-jenkins

### CODE REVIEW

**Comment by sorta** [comment]
I have recently thought about this PR, and I'm wondering if it makes more sense to hide this behind a feature flag rather than use an epic branch.

Since this is a new page, it would be rather easy to hide the page at the route level. Just redirect away if the feature flag is disabled. And once the work is done the feature flag can be easily removed. And perhaps a naming convention could make it clear that the flag is meant to be temporary. So maybe something like `wip-travis-vs-jenkins`.

An epic branch process adds a little bit of organizational overhead, and maybe makes more sense in cases where it is harder or more complicated to hide the work in progress. For example, major updates to an existing page.

**Comment by artursmirnov** [comment]
@sorta it totally makes sense to me 👍

**Comment by sorta** [comment]
Everything here has been code reviewed at some point, but feel free to review again if you get a chance. Thanks!

**Comment by sorta** [comment]
Thanks so much for the reviews @artursmirnov & @piotr-travisci !

**Pull request merged**
