### PR TITLE
Early WIP: Web Notifications

### PR DESCRIPTION
**Pull request by simi**
I started first iteration for html notifications feature requested in https://github.com/travis-ci/travis-ci/issues/1109. No time to code review yet. Just tech demo for http://www.w3.org/TR/notifications/. I will be glad to finish this. I just need to know if this is wanted and if someone can help me with programming-less problems.
## Screenshot from my linux Chrome:

travis-notify
# Problems:
- [ ] commit message is not available everytime
- [ ] UI for notification control (enable/disable) is not done
- [x] design icons for passed, failed, errored and canceled notifications (I did some ugly ones for testing).
- [ ] decide what will be best copy for those notifications, currently it is (title, body):

```
"repo.slug" #"build.number" "build.state"
"commit.message"
```

### CODE REVIEW

**Comment by simi** [comment]
I think i can reuse icons from https://github.com/travis-ci/travis-web/pull/333.

Are you still interested in this feature? I can try to finish it (probably start again, since a lot of changes was made - ember-cli and stuff).

**Comment by backspace** [comment]
This pull request has languished, I’m sorry that happened to your work, @simi. Can @drogus and/or @joshk confirm that this functionality is still desired?

**Comment by simi** [comment]
I would like to implement this to Travis CI. I can start from scratch, since this is non-mergable.

It will be nice if someone can take care of UI/UX part.

I can try to force push some prototype for actual code in this branch, no need to close.

Ping me with news.

**Comment by joshk** [comment]
I'd still be interested in us getting this merged in, at least for testing.

This would need to work smoothly in instances of having multiple tabs open. And we would need to find a place to putting the setting so it can be turned on. Maybe in the user drop down?

**Comment by simi** [comment]
I'm still interested into this. I can try to make second round and try to implement it again.

**Comment by phansch** [comment]
Not sure if the :+1: get noticed. Just saying that this would be super super useful. Currently a person always has to check manually if a build has finished - either in the browser or in the configured notification channel. The browser notification would allow to keep working without having to keep the Travis Build in mind.

**Comment by simi** [comment]
I'm still around to finish this, but I think there were some problems when I firstly introduced this:

1. I had some Ember problems, but I think they will be gone now since I know ember better now.
2. I was awaiting appropriate images for notifications.
3. I was waiting for decision which repos should be using this notifications. (all in currently opened panel?, just current build?, make it configurable?, when configurable, where to store that configuration?)

I can try to do second run with some boilerplate images, but I will need to wait for those decisions.

I can start with some basic implementation - show notifications only for currently opened project, build or job. And maybe extend that later.

Is there anyone from Travis team interested in this and able to lead me to right way here?

**Comment by backspace** [comment]
Hey! We are still into this if you are.

I agree that it makes sense to start small with this. We can just show notifications for whatever job is currently onscreen. Eventually we’ll probably want more configurability, but we can defer that until we have a better sense of how this feels.

For images, let’s start with the various coloured favicons within [`public/images`](https://github.com/travis-ci/travis-web/tree/master/public/images). Before this is shipped, we can get some better images.

I wonder if the interface for turning this on could be part of the [beta features route](https://travis-ci.org/features), despite that being API-backed, where this would be on a per-browser basis. It should be easy enough to make it look like the other features but act differently beneath.

Maybe you’ll end up closing this PR and opening a new one, as things have changed dramatically in this repository. Let me know if you need anything else?

**Comment by ctrlaltjustine** [comment]
I would prefer we **not** use the favicons since they're really only designed to be viewed at 16x16px

Here's some svgs to use instead:
**Passed:** https://ok.hellojustine.com/view/WebNotification-img-green.svg
**Running:** https://ok.hellojustine.com/view/WebNotification-img-yellow.svg
**Cancelled:** https://ok.hellojustine.com/view/WebNotification-img-grey.svg
**Failed:** https://ok.hellojustine.com/view/WebNotification-img-red.svg

**Pull request closed without merging**
