### PR TITLE
Removing Henrik (😢) and adding Natalia (🎉) to the Team Page

### PR DESCRIPTION
**Pull request by ctrlaltjustine**

### CODE REVIEW

**Comment by ctrlaltjustine** [comment]
Since @lislis is on support this week and @clekstro is on vacation, perhaps @backspace can take a look at this? I'd love to get this merged in and shipped sooner rather than later <333

**Comment by backspace** [comment]
This is a holiday for me 😬

But I’ll do it!

**Comment by ctrlaltjustine** [comment]
I'm so sorry I didn't realize you were on leave. Thank you though.

**Comment by backspace** [comment]
It’s okay, the calendar event seems to have disappeared anyway! Not sure what that’s about. But it’s deployed now. 😀

**Comment by ctrlaltjustine** [comment]
Thank you very much!

**Pull request merged**
