### PR TITLE
Adjust builds for more speed

### PR DESCRIPTION
**Pull request by backspace**
I’m going through [this](https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md).

### CODE REVIEW

**Comment by artursmirnov** [comment]
I have also noticed, that the app uses `ember-composable-helpers`. [Whitelisting](https://github.com/DockYard/ember-composable-helpers#configuration) only the helpers that we use may help to improve build performance as well.

**Comment by backspace** [comment]
oh nice, thanks, I’ll check that out when I can come back to this. Sadly most of my changes haven’t made much of a difference for build times, but there are some changes and updates we should do anyway.

**Comment by artursmirnov** [comment]
On one of my previous apps the `ember-cli-mirage` made a huuuge affect to build time. When I installed it and created some factories, the build time increased like twice! And I also heard the same from other ember devs. Probably it makes sense to ask Sam at Inside EmberMap about what can affect the build performance and maybe he can give some advice on improvement.

In fact, building `travis-web` with mirage takes 23s for me:
```bash
$ time ember b
Built project successfully. Stored in "dist/".
ember b  23.11s user 3.48s system 107% cpu 24.827 total
```
Without mirage it takes 19s:
```bash
$ time ember b
Built project successfully. Stored in "dist/".
ember b  19.36s user 2.78s system 111% cpu 19.898 total
```

Also production build complains about minification of `vendor.js`, which means it's too big. The way to improve it may be to sanitize the addons that we use. And, of course, the upcoming tree-shaking would help with that.

**Comment by backspace** [comment]
yeah, the Mirage update I made in this branch actually did speed up the build significantly. I’m starting to wonder whether we should stop using it entirely because of the number of times I’ve had problems with slight differences between the true and Mirage APIs, most recently [here](https://github.com/travis-ci/travis-web/pull/1751). But that would be a significant undertaking.

I generated some build time graphs and Mirage was indeed quite slow.

**Pull request closed without merging**
