### PR TITLE
add osx_image to keys-map

### PR DESCRIPTION
**Pull request by lislis**
screen shot 2015-11-13 at 13 12 46
Looks like this

### CODE REVIEW

**Comment by simi** [comment]
Is that compatible with http://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html?

**Comment by lislis** [comment]
@simi I believe so. Do you think otherwise?

**Comment by simi** [comment]
I don't know. I had an idea to ask and ensure that's in your mind also.

**Comment by lislis** [comment]
The guideline says to only use Apple product names when the software is actually using it or is compatible with it. I think that's the case. Plus, 'Xcode' is written the way they want it to be written :D 
Thanks for checking in on that anyway :+1:

**Comment by simi** [comment]
:+1: OK, thanks for clarification.

**Pull request merged**
