### PR TITLE
Subscribe new repositories to pusher

### PR DESCRIPTION
**Pull request by drogus**

### CODE REVIEW

**Comment by joshk** [comment]
will this work for Enterprise as well? (where all pusher communication should be via private channels?)

**Comment by drogus** [comment]
@joshk oops, I haven't seen your comment when I clicked merge. I'm not sure to be honest, I wasn't aware that even public repos use private channes on enterprise, I'll double check it

**Comment by joshk** [comment]
@drogus hey, sorry, did you see my comment above?

**Comment by joshk** [comment]
Ah, ok. For reference, with Enterprise you can have a 'public' repo, but all communication from us should be 'private'.

**Comment by joshk** [comment]
It might mean that you need to check if this is an Enterprise install.

**Comment by drogus** [comment]
This should be fixed with https://github.com/travis-ci/travis-web/pull/601

**Pull request merged**
