### PR TITLE
show Dart task matrix expansion key

### PR DESCRIPTION
**Pull request by kevmoo**
CC @BanzaiMan @a14n

### CODE REVIEW

**Comment by kevmoo** [comment]
@a14n didn't know you had the keys here! 😄

**Comment by kevmoo** [comment]
> @a14n didn't know you had the keys here! 😄

NM. I guess anyone can approve. 🐑

**Comment by lislis** [comment]
Hey there! Thanks for the update! It'll be online 🔜

**Comment by kevmoo** [comment]
Thanks, @lislis 

A couple of things.

1) I noticed the output get cropped in undesirable ways

dart_task_layout_weird

2) I noticed that if we have more than just a single string for the task we got `[Object object]` instead

*this is with some manual CSS tweaking to show the full value*
un_clipped_weird_output

CC @BanzaiMan @a14n

**Comment by kevmoo** [comment]
Filled an issue to track: https://github.com/travis-ci/travis-ci/issues/7537

**Pull request merged**
