### PR TITLE
New syntax codemods

### PR DESCRIPTION
**Pull request by artursmirnov**
This PR is to update `travis-web` templates syntax to angle brackets invocation (https://guides.emberjs.com/release/reference/syntax-conversion-guide/)

### CODE REVIEW

**Comment by artursmirnov** [comment]
This PR is ready for merge. I don't know if it's reviewable, mostly for information. But curious ones could dig in deeper 😄 

It's mostly a result of a codemod run, but also includes some manual changes, like [SvgImage](https://github.com/travis-ci/travis-web/blob/as-new-syntax-codemods/app/templates/components/svg-image.hbs) component that wraps `svg-jar` (which appeared to be a helper), references to `this` context in templates and some formatting changes.

**Comment by clekstro** [comment]
@artursmirnov I poked around in the PR envs, things seem fine. Thanks!

**Comment by artursmirnov** [comment]
@clekstro thanks for double-checking, it's always good to have another pair of eyes on such massive changes!

**Comment by piotr-travisci** [comment]
👍job @artursmirnov 
Thank you!  🎉

**Comment by artursmirnov** [comment]
Thanks everyone for reviews!

**Comment by drogus** [comment]
Awesome :D

**Pull request merged**
