### PR TITLE
MVD with user-facing feature flags

### PR DESCRIPTION
**Pull request by clekstro**

### CODE REVIEW

**Comment by clekstro** [comment]
@joshk I think I've incorporated the changes you were looking for. Could you take another look when you're around?

**Comment by clekstro** [comment]
Changes desired in the UI:

- [ ] Change URL of features page to `/settings/features`
- [ ] Stub out participation in the `beta` program, only show link if present.
- [ ] Change "See what's new" in sidebar from button to link

**Comment by clekstro** [comment]
Few things need to happen before we merge this in:

- [ ] Remove mocked out data in development/production
- [ ] API Endpoints deployed

**Comment by lislis** [comment]
Closing in favour of https://github.com/travis-ci/travis-web/pull/937

**Pull request closed without merging**
