### PR TITLE
Update Plans page

### PR DESCRIPTION
**Pull request by speedywizard**

### CODE REVIEW

**Comment by speedywizard** [comment]
@artursmirnov , please take a look

**Review by artursmirnov — COMMENTED** [review]
Hey @speedywizard, thank you for addressing all the feedback! Everything looks great to me, I have just a couple of minor comments. Although, I didn't pay too much attention to the tests yet, as I assume they are not ready yet.

Visually it looks very good to me as well - very clean and close to design 👍  Great job, thank you!

**Review by artursmirnov — APPROVED** [review]
Hey @speedywizard, thank you for all the improvements and for implementing all the feedback! It looks great to me both code-wise and visually 👍 Great job!

**Comment by artursmirnov** [comment]
As agreed, the tests will be fixed separately, so I'm approving and merging this PR.

**Pull request merged**
