### PR TITLE
Update GitHub icons

### PR DESCRIPTION
**Pull request by clekstro**
This will bring us into compliance with the [GitHub logo guidelines](https://github.com/logos).

### CODE REVIEW

**Comment by clekstro** [comment]
@lislis I thought that it was just the owner page that was having issues (tooltip not displaying when hovering over the link), but it looks like the Build History page is affected as well. Could you have a look?
screen shot 2017-08-28 at 9 46 51 am

**Comment by lislis** [comment]
looking!

**Comment by lislis** [comment]
Opened a PR here https://github.com/travis-ci/travis-web/pull/1268

**Comment by clekstro** [comment]
This looks good in the PR envs, merging.

**Pull request merged**
