### PR TITLE
Update settings to use atomic API

### PR DESCRIPTION
**Pull request by backspace**
This is a continuation of [this PR](https://github.com/travis-ci/travis-web/pull/696), with a new branch name to [get staging deployments](https://github.com/travis-ci/travis-web/pull/700) 😬

### CODE REVIEW

**Comment by backspace** [comment]
An example place to try this out is [here](https://bd-atomic-settings-staging-staging.test-deployments.travis-ci.org/travis-ci/travis-ci/settings), as long as the staging API survives. The last commit fixed the bug I was stuck on. So this can be deployed when the API is.

**Comment by backspace** [comment]
I was hoping to deploy this today but I’m getting some seemingly-unrelated test failures so 🤔 probably have to wait until tomorrow.

**Comment by backspace** [comment]
wellll the tests passed here soooo that’s weird, I `nom`ed and I `bom`ed and they now pass locally for me. But there are no deployment on this PR so I’d like to look at that tomorrow before merging… 😞

**Comment by clekstro** [comment]
We should wait on merging this until https://github.com/travis-ci/travis-api/pull/333 and https://github.com/travis-ci/travis-api/pull/332 have both been merged/deployed and we can double-check that ENV vars are not being deleted/overridden.

**Comment by backspace** [comment]
I’ve updated this to target the API change made in travis-ci/travis-api#332. I’ve tested it against the production API that includes travis-ci/travis-api#333 and confirmed that environment variables are no longer deleted, but for true confidence I’d like to restore pull request deployments for a final test before I deploy this. Hopefully that will all be back tomorrow and I can remove the troubleshooting mess throughout this branch and merge it.

**Comment by backspace** [comment]
The PR deployments are back and this is working against the API changes that are now in production, so I think this is ready to merge and deploy. It’s a holiday for me on Monday, so this could be merged in my absence as I don’t anticipate any problems, but I could do it on Tuesday too.

**Comment by backspace** [comment]
I’ve tested this on the staging deployments, all looks well. Merging and deploying.

**Pull request merged**
